// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhK-4TADK43KIK3qs2HlMTQ9Nl4JvPjM',
    appId: '1:185129230842:web:6cc52917f9273f30924443',
    messagingSenderId: '185129230842',
    projectId: 'flutter-ecomer-1adf5',
    authDomain: 'flutter-ecomer-1adf5.firebaseapp.com',
    storageBucket: 'flutter-ecomer-1adf5.firebasestorage.app',
    measurementId: 'G-R24HEJP52C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn0-9Yq56QwWmM5-9voMNQ9FMVcJOKRlI',
    appId: '1:185129230842:android:49f177fdafe796a8924443',
    messagingSenderId: '185129230842',
    projectId: 'flutter-ecomer-1adf5',
    storageBucket: 'flutter-ecomer-1adf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqWxJJrtrRnDacJ0tyJLClBWs7E5qk2I',
    appId: '1:185129230842:ios:a2ce9712f17d751c924443',
    messagingSenderId: '185129230842',
    projectId: 'flutter-ecomer-1adf5',
    storageBucket: 'flutter-ecomer-1adf5.firebasestorage.app',
    iosBundleId: 'com.example.productListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeqWxJJrtrRnDacJ0tyJLClBWs7E5qk2I',
    appId: '1:185129230842:ios:a2ce9712f17d751c924443',
    messagingSenderId: '185129230842',
    projectId: 'flutter-ecomer-1adf5',
    storageBucket: 'flutter-ecomer-1adf5.firebasestorage.app',
    iosBundleId: 'com.example.productListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjhK-4TADK43KIK3qs2HlMTQ9Nl4JvPjM',
    appId: '1:185129230842:web:cef9bb76dd156905924443',
    messagingSenderId: '185129230842',
    projectId: 'flutter-ecomer-1adf5',
    authDomain: 'flutter-ecomer-1adf5.firebaseapp.com',
    storageBucket: 'flutter-ecomer-1adf5.firebasestorage.app',
    measurementId: 'G-ZKW2ZX1247',
  );
}
